In [44]:
import scipy
import scipy.linalg   # SciPy Linear Algebra Library
import numpy as np
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt

In [45]:
def scaling(df):
    from sklearn.preprocessing import MinMaxScaler
    scaler=MinMaxScaler(feature_range=(0, 1)).fit(df) 
    scaled_features=scaler.transform(df) 
    return scaled_features

## Load datasets

In [46]:
# Source profile

A =pd.read_excel("Heavymetal_sources_git.xlsx")

In [47]:
A

,Element,Coal,Fuel oil/Traffic,Crust,Industry average,Biomass/Wood burning
0,K,337000,0,2090,3.000000e+02,50280
1,Ca,2774000,139000,4150,6.500000e+03,40
2,Na,618300,1393750,2360,9.000000e+03,560
3,Mg,378600,9200,2330,3.136000e+05,20
4,Mn,19800,0,950000,4.212100e+05,2400
5,Cu,39500,0,55000,1.140000e+05,2200
6,As,39200,270,1800,1.000000e+03,200
7,Cd,0,2800,200,1.400000e+04,40
8,Pb,25000,2300,12500,1.020183e+07,1160


In [48]:
A1=A.drop(["Element"], axis=1)

In [49]:
A1

,Coal,Fuel oil/Traffic,Crust,Industry average,Biomass/Wood burning
0,337000,0,2090,3.000000e+02,50280
1,2774000,139000,4150,6.500000e+03,40
2,618300,1393750,2360,9.000000e+03,560
3,378600,9200,2330,3.136000e+05,20
4,19800,0,950000,4.212100e+05,2400
5,39500,0,55000,1.140000e+05,2200
6,39200,270,1800,1.000000e+03,200
7,0,2800,200,1.400000e+04,40
8,25000,2300,12500,1.020183e+07,1160


In [50]:
# Sample profile

B = pd.read_excel("IGP_test_bihar_git.xlsx")

In [51]:
B

,Sample ID,K,Ca,Na,Mg,Mn,Cu,As,Cd,Pb
0,M01,2251,19018.0,12254.0,1332,16.463000,3.958000,0.701000,0.478000,4.384000
1,M02,860,3739.0,2900.0,449,6.538000,3.418000,0.127000,0.418000,2.952000
2,M03,722,4164.0,4014.0,540,11.146000,2.512000,0.147000,0.474000,2.516000
3,M04,1153,11909.0,5824.0,795,8.359000,9.890000,0.564000,0.522000,2.557000
4,M05,1935,12021.0,8214.0,1111,13.224000,7.815000,0.598000,0.453000,4.362000
5,M06,799,4850.0,3933.0,467,5.608000,3.493000,0.190000,0.164000,2.181000
6,M07,1347,8778.0,6093.0,590,7.110000,5.258000,0.271000,0.362000,3.670000
7,M08,2305,13991.0,8198.0,1083,46.363000,11.716000,1.487000,0.840000,7.665000
8,M09,2092,14023.0,9388.0,847,15.072000,4.875000,1.161000,0.428000,4.440000
9,M10,1129,5053.0,3368.0,457,99.187000,5.740000,1.075000,0.459000,4.717000


In [52]:
B1 = B.drop(["Sample ID"], axis =1)

In [53]:
# Description of sample data

B1.describe()

,K,Ca,Na,Mg,Mn,Cu,As,Cd,Pb
count,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000
mean,1856.142857,9007.095238,3825.000000,789.714286,22.625184,3.660462,0.885375,0.342480,2.392415
std,1273.851023,5088.861561,3320.966922,397.838679,24.009083,3.108364,0.770100,0.237648,1.990119
min,468.000000,2444.000000,523.000000,281.000000,2.175061,0.088771,0.127000,0.023078,0.065047
25%,860.000000,4850.000000,1319.000000,467.000000,7.110000,1.356401,0.320956,0.117326,0.436822
50%,1707.000000,8001.000000,2900.000000,694.000000,13.224000,3.384211,0.603964,0.362000,2.209108
75%,2305.000000,12990.000000,5824.000000,1046.000000,30.308341,4.875000,1.161000,0.474000,3.670000
max,5502.000000,19018.000000,12254.000000,1888.000000,99.187000,11.716000,3.267257,0.840000,7.665000


In [54]:
#B1 = B[:1]

In [55]:
B1

,K,Ca,Na,Mg,Mn,Cu,As,Cd,Pb
0,2251,19018.0,12254.0,1332,16.463000,3.958000,0.701000,0.478000,4.384000
1,860,3739.0,2900.0,449,6.538000,3.418000,0.127000,0.418000,2.952000
2,722,4164.0,4014.0,540,11.146000,2.512000,0.147000,0.474000,2.516000
3,1153,11909.0,5824.0,795,8.359000,9.890000,0.564000,0.522000,2.557000
4,1935,12021.0,8214.0,1111,13.224000,7.815000,0.598000,0.453000,4.362000
5,799,4850.0,3933.0,467,5.608000,3.493000,0.190000,0.164000,2.181000
6,1347,8778.0,6093.0,590,7.110000,5.258000,0.271000,0.362000,3.670000
7,2305,13991.0,8198.0,1083,46.363000,11.716000,1.487000,0.840000,7.665000
8,2092,14023.0,9388.0,847,15.072000,4.875000,1.161000,0.428000,4.440000
9,1129,5053.0,3368.0,457,99.187000,5.740000,1.075000,0.459000,4.717000


In [56]:
A1_scaled = scaling(A1.values)

In [57]:
A1_scaled

array([[1.21485220e-01, 0.00000000e+00, 1.98989261e-03, 0.00000000e+00,
        1.00000000e+00],
       [1.00000000e+00, 9.97309417e-02, 4.15877027e-03, 6.07751776e-04,
        3.97930760e-04],
       [2.22891132e-01, 1.00000000e+00, 2.27416298e-03, 8.52812976e-04,
        1.07441305e-02],
       [1.36481615e-01, 6.60089686e-03, 2.24257738e-03, 3.07110696e-02,
        0.00000000e+00],
       [7.13770728e-03, 0.00000000e+00, 1.00000000e+00, 4.12594839e-02,
        4.73537604e-02],
       [1.42393655e-02, 0.00000000e+00, 5.76963571e-02, 1.11453834e-02,
        4.33744528e-02],
       [1.41312185e-02, 1.93721973e-04, 1.68456517e-03, 6.86171360e-05,
        3.58137684e-03],
       [0.00000000e+00, 2.00896861e-03, 0.00000000e+00, 1.34293538e-03,
        3.97930760e-04],
       [9.01225667e-03, 1.65022422e-03, 1.29500948e-02, 1.00000000e+00,
        2.26820533e-02]])

In [58]:
a1=np.asarray(A1_scaled)

In [59]:
a1

array([[1.21485220e-01, 0.00000000e+00, 1.98989261e-03, 0.00000000e+00,
        1.00000000e+00],
       [1.00000000e+00, 9.97309417e-02, 4.15877027e-03, 6.07751776e-04,
        3.97930760e-04],
       [2.22891132e-01, 1.00000000e+00, 2.27416298e-03, 8.52812976e-04,
        1.07441305e-02],
       [1.36481615e-01, 6.60089686e-03, 2.24257738e-03, 3.07110696e-02,
        0.00000000e+00],
       [7.13770728e-03, 0.00000000e+00, 1.00000000e+00, 4.12594839e-02,
        4.73537604e-02],
       [1.42393655e-02, 0.00000000e+00, 5.76963571e-02, 1.11453834e-02,
        4.33744528e-02],
       [1.41312185e-02, 1.93721973e-04, 1.68456517e-03, 6.86171360e-05,
        3.58137684e-03],
       [0.00000000e+00, 2.00896861e-03, 0.00000000e+00, 1.34293538e-03,
        3.97930760e-04],
       [9.01225667e-03, 1.65022422e-03, 1.29500948e-02, 1.00000000e+00,
        2.26820533e-02]])

In [60]:
ones1 = np.ones(5, dtype = None, order = 'C')

In [61]:
a_matrix = np.vstack([a1,ones1])

In [62]:
a_matrix

array([[1.21485220e-01, 0.00000000e+00, 1.98989261e-03, 0.00000000e+00,
        1.00000000e+00],
       [1.00000000e+00, 9.97309417e-02, 4.15877027e-03, 6.07751776e-04,
        3.97930760e-04],
       [2.22891132e-01, 1.00000000e+00, 2.27416298e-03, 8.52812976e-04,
        1.07441305e-02],
       [1.36481615e-01, 6.60089686e-03, 2.24257738e-03, 3.07110696e-02,
        0.00000000e+00],
       [7.13770728e-03, 0.00000000e+00, 1.00000000e+00, 4.12594839e-02,
        4.73537604e-02],
       [1.42393655e-02, 0.00000000e+00, 5.76963571e-02, 1.11453834e-02,
        4.33744528e-02],
       [1.41312185e-02, 1.93721973e-04, 1.68456517e-03, 6.86171360e-05,
        3.58137684e-03],
       [0.00000000e+00, 2.00896861e-03, 0.00000000e+00, 1.34293538e-03,
        3.97930760e-04],
       [9.01225667e-03, 1.65022422e-03, 1.29500948e-02, 1.00000000e+00,
        2.26820533e-02],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00]])

## QR Decomposition

In [63]:
Q, R = np.linalg.qr(a_matrix, mode='reduced')

In [64]:
Q

array([[-8.41620236e-02, -7.13658780e-02, -2.82190718e-02,
         2.20884581e-02,  9.03966451e-01],
       [-6.92775826e-01, -4.95214482e-01, -2.68489220e-01,
         1.96240944e-01, -2.48200667e-01],
       [-1.54413588e-01,  7.93856566e-01, -3.12419479e-01,
         2.24696081e-01, -1.55664164e-01],
       [-9.45511636e-02, -7.40709723e-02, -3.34093531e-02,
        -1.39054780e-03, -3.92667604e-02],
       [-4.94483106e-03, -4.19301004e-03,  8.43254810e-01,
         2.52383782e-01, -1.80357889e-01],
       [-9.86468823e-03, -8.36484326e-03,  4.52494255e-02,
         9.18178576e-03,  2.25986214e-02],
       [-9.78976654e-03, -8.12216012e-03, -2.10483696e-03,
         2.96240630e-03, -3.95222475e-04],
       [-0.00000000e+00,  1.85787977e-03, -5.21291364e-04,
        -8.27186439e-04, -1.07347177e-04],
       [-6.24347356e-03, -3.76808907e-03,  8.29663439e-03,
        -8.87565112e-01, -1.72281947e-01],
       [-6.92775826e-01,  3.37347892e-01,  3.39404457e-01,
        -2.42792427e-01

In [65]:
Q.shape

(10, 5)

In [66]:
R

array([[-1.44346838, -0.91691692, -0.70199893, -0.70279043, -0.77971127],
       [ 0.        ,  1.08132326,  0.33204754,  0.33141675,  0.27363906],
       [ 0.        ,  0.        ,  1.18341574,  0.38154118,  0.34979626],
       [ 0.        ,  0.        ,  0.        , -1.1195747 , -0.22598366],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.07168686]])

In [67]:
R.shape

(5, 5)

In [68]:
R_inv = np.linalg.inv(R)

In [69]:
Q_trans = np.transpose(Q)

In [70]:
x1 = np.matmul(R_inv, Q_trans)

In [71]:
ones = np.ones(1, dtype = None, order = 'C')

In [72]:
#B1[2:3]

## Calculation of source apportionment

In [73]:
X_arr=[]
x_df = []
for i in range(1,(len(B1)+1)):
    B_arr = B1[(i-1):i]
    #print(B_arr)
    b1=np.asarray(B_arr)
    #print(b1)
    b1=b1.T
    b1=scaling(b1)
    b_matrix = np.vstack([b1,ones])
    X = np.matmul(x1,b_matrix)
    x_df.append(X)
    print(x_df)
    X_sum = sum(X)
    X_arr.append(X_sum)
    #print(X_arr)
    #B_arr=[]
    #print(B_arr)

[array([[ 0.90672989],
       [ 0.37535981],
       [-0.07169098],
       [-0.07805241],
       [-0.05924818]])]
[array([[ 0.90672989],
       [ 0.37535981],
       [-0.07169098],
       [-0.07805241],
       [-0.05924818]]), array([[ 0.87440515],
       [ 0.46968649],
       [-0.11749722],
       [-0.12105021],
       [ 0.01380018]])]
[array([[ 0.90672989],
       [ 0.37535981],
       [-0.07169098],
       [-0.07805241],
       [-0.05924818]]), array([[ 0.87440515],
       [ 0.46968649],
       [-0.11749722],
       [-0.12105021],
       [ 0.01380018]]), array([[ 0.84255566],
       [ 0.64258971],
       [-0.13613485],
       [-0.14282127],
       [-0.06180471]])]
[array([[ 0.90672989],
       [ 0.37535981],
       [-0.07169098],
       [-0.07805241],
       [-0.05924818]]), array([[ 0.87440515],
       [ 0.46968649],
       [-0.11749722],
       [-0.12105021],
       [ 0.01380018]]), array([[ 0.84255566],
       [ 0.64258971],
       [-0.13613485],
       [-0.14282127],
       [-0.0

In [74]:
X_arr

[array([1.07309814]),
 array([1.11934439]),
 array([1.14438454]),
 array([1.04016155]),
 array([1.08871245]),
 array([1.11326195]),
 array([1.08874267]),
 array([1.07141127]),
 array([1.08325106]),
 array([1.10065799]),
 array([1.06146218]),
 array([1.00883803]),
 array([1.03287921]),
 array([0.99911242]),
 array([1.01573113]),
 array([0.98438521]),
 array([1.03667092]),
 array([1.02284304]),
 array([1.01348477]),
 array([1.00979431]),
 array([1.01427505])]

In [75]:
np.average(X_arr)

1.053452489301452

In [76]:
X

array([[ 0.98940208],
       [ 0.01232645],
       [-0.02138996],
       [-0.02355168],
       [ 0.05748816]])

In [77]:
#X=pd.DataFrame(X)

In [78]:
x_df = np.asarray(x_df)

In [79]:
x_df1=np.squeeze(x_df)

In [80]:
x_df1

array([[ 0.90672989,  0.37535981, -0.07169098, -0.07805241, -0.05924818],
       [ 0.87440515,  0.46968649, -0.11749722, -0.12105021,  0.01380018],
       [ 0.84255566,  0.64258971, -0.13613485, -0.14282127, -0.06180471],
       [ 0.94052431,  0.24313736, -0.04142465, -0.04736893, -0.05470654],
       [ 0.89712298,  0.40146983, -0.0874573 , -0.09257876, -0.0298443 ],
       [ 0.87092914,  0.5122329 , -0.10946519, -0.11507349, -0.0453614 ],
       [ 0.89250867,  0.41354207, -0.08739909, -0.09311774, -0.03679123],
       [ 0.91461714,  0.31621548, -0.07002881, -0.07702385, -0.01236869],
       [ 0.89714406,  0.39301313, -0.0820389 , -0.0882723 , -0.03659494],
       [ 0.89174976,  0.37419311, -0.08272907, -0.10469538,  0.02213957],
       [ 0.93860871,  0.17159682, -0.06560746, -0.06961374,  0.08647785],
       [ 1.00218818, -0.12547547, -0.02248544, -0.02209678,  0.17670753],
       [ 0.97090538,  0.08074857, -0.04056808, -0.04112359,  0.06291693],
       [ 0.99534886, -0.01438191, -0.0

In [81]:
x_df1.shape

(21, 5)

In [82]:
x_final=pd.DataFrame(x_df1, columns=['x1','x2','x3','x4','x5'])

## Final source apportionment (Here source x1, x2...x5 refers to the sources mentioned in source profile)

In [83]:
x_final

,x1,x2,x3,x4,x5
0,0.906730,0.375360,-0.071691,-0.078052,-0.059248
1,0.874405,0.469686,-0.117497,-0.121050,0.013800
2,0.842556,0.642590,-0.136135,-0.142821,-0.061805
3,0.940524,0.243137,-0.041425,-0.047369,-0.054707
4,0.897123,0.401470,-0.087457,-0.092579,-0.029844
5,0.870929,0.512233,-0.109465,-0.115073,-0.045361
6,0.892509,0.413542,-0.087399,-0.093118,-0.036791
7,0.914617,0.316215,-0.070029,-0.077024,-0.012369
8,0.897144,0.393013,-0.082039,-0.088272,-0.036595
9,0.891750,0.374193,-0.082729,-0.104695,0.022140


In [43]:
#x_final.to_excel('D:/IIITK_final/IIITK/Fog_SKD/New_data/calculated_X_inverse1_bihar.xlsx')